
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test
    driverClassName: org.mariadb.jdbc.Driver
    max-active: 100
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-test-query: SELECT 1
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 3000
  flyway:
    schemas: test
    baseline-on-migrate: true #BE EXTRA CAREFUL WITH BASELINE
    validate-on-migrate: true #true to populate local DB
    table: schema_version
    enabled: true #true to enable flyway
  jpa:
    hibernate:
      ddl-auto: validate


server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate: INFO